language: rust
# cache dependencies: https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache
cache:
  directories:
    - ~/.cargo
rust:
  - stable
os:
  - linux
git:
  depth: 5
script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$JOB" == "api_docs" ]]; then
        echo "Running cargo docs on stable Rust on Linux" &&
        make docs
      fi
after_success:
  # upload the documentation from the build if it's from Rust stable, Linux and not a pull request:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_PULL_REQUEST" == false && "$JOB" == "api_docs" ]]; then
        echo '<meta http-equiv=refresh content=0;url=rusoto_core/index.html>' > target/doc/index.html \
        && mkdir target/doc/rusoto/ && echo '<meta http-equiv=refresh content=0;url=../rusoto_core/index.html>' > target/doc/rusoto/index.html \
        && sudo pip install ghp-import && ghp-import -n target/doc \
        && git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages \
        && cd ..
      fi
env:
  global:
    - RUST_BACKTRACE=1
    - CARGO_INCREMENTAL=0
  matrix:
    - JOB=api_docs
branches:
  only:
    - master
    - auto
notifications:
  email: false
matrix:
  fast_finish: true
