language: rust
rust:
  - stable
  - beta
  - nightly
install: "pip install --user -r codegen/requirements.txt"
script:
  - cargo build --verbose --features all
  - cargo test --verbose
notifications:
  email: false
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
