language: rust
rust:
  - stable
  - beta
  - nightly
notifications:
  email: false
script:
  - cargo build --verbose
  - cargo test --verbose --features ci
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
