language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --features all
  - cargo test --verbose --features all
branches:
  only:
    - master
notifications:
  email: false
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
