language: rust
rust:
  - stable
  - beta
  - nightly
install: "pip install --user -r codegen/requirements.txt"
notifications:
  email: false
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
