[package]
name = "rusoto"
version = "0.1.0"
authors = ["Anthony DiMarco <anthony.dimarco@dualspark.com>"]

[dependencies]
xml-rs = "*"
time = "*"
openssl = "*"
hyper = "0.6.1"
url = "*"
rustc-serialize = "*"
regex = "0.1.41"
