[package]
name = "rusoto"
version = "0.12.1"
authors = [
  "Anthony DiMarco <ocramida@gmail.com>",
  "Jimmy Cuadra <jimmy@jimmycuadra.com>",
  "Matthew Mayer <matthewkmayer@gmail.com>",
]
license = "MIT"
readme = "README.md"
keywords = ["AWS", "Amazon"]
description = "AWS SDK for Rust"
repository = "https://github.com/rusoto/rusoto"
documentation = "http://rusoto.github.io/rusoto/rusoto/index.html"
exclude = [".gitignore", ".travis.yml", "docgen.sh"]
build = "build.rs"

[features]
default = ["with-syntex"]
with-syntex = ["rusoto_codegen/with-syntex"]
nightly = ["serde_macros", "rusoto_codegen/nightly"]
all = ["dynamodb", "ecs", "kms", "s3", "sqs"]
dynamodb = []
ecs = []
kms = []
s3 = []
sqs = []

[build-dependencies.rusoto_codegen]
path = "codegen"
default-features = false

[dependencies]
serde = "0.7.0"
serde_json = "0.7.0"
xml-rs = "^0.1.26"
time = "^0.1.34"
openssl = "^0.7.7"
hyper = "^0.7.2"
url = "^0.2.37"
rustc-serialize = "^0.3.18"
regex = "^0.1.51"
chrono = "^0.2.19"
log = "^0.3.3"
serde_macros = { version = "0.7.0", optional = true }

[dev-dependencies]
env_logger = "^0.3.2"
