[package]
name = "rusoto_codegen"
version = "0.1.0"
authors = [
  "Anthony DiMarco <ocramida@gmail.com>",
  "Jimmy Cuadra <jimmy@jimmycuadra.com>",
  "Matthew Mayer <matthewkmayer@gmail.com>",
]
description = "Code generation library for Rusoto."
license = "MIT"
repository = "https://github.com/rusoto/rusoto"
build = "build.rs"

[features]
default = ["with-syntex"]
with-syntex = ["serde_codegen", "syntex"]
nightly = ["serde_macros"]

[build-dependencies]
serde_codegen = { version = "0.7.0", optional = true }
syntex = { version = "0.30.0", optional = true }

[dependencies]
Inflector = "0.2.0"
regex = "0.1.55"
serde = "0.7.0"
serde_codegen = { version = "0.7.1", optional = true }
serde_json = "0.7.0"
serde_macros = { version = "0.7.0", optional = true }
syntex = { version = "0.31.0", optional = true }
